# Generated by Django 5.2.11 on 2026-02-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_alter_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
